[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sbbbin"
version = "0.2.0"
authors = [
    {name = "Vahid Rezanezhad"},
    {name = "Staatsbibliothek zu Berlin - Preußischer Kulturbesitz"},
    {name = "Janik Haitz", email = "jahtz.dev@proton.me"},
    {name = "Centre for Philology and Digitality (ZPD), University of Würzburg"}
]
description = "Pixelwise binarization with selectional auto-encoders in Keras"
readme = "README.md"
license.file = "LICENSE"
requires-python = ">=3.8, <3.11"

classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Image Processing",
]

dependencies = [
    "rich_click~=1.8.8",
    "tensorflow~=2.11.1",
    "opencv-python~=4.11.0.86",
    "numpy~=1.26.4"
]
scripts = { sbbbin = "cli.sbbbin_cli:cli" }

[project.urls]
repository = "https://github.com/jahtz/sbbbin"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests", "assets"]
