[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "sbbbin"
version = "0.3.0"
description = "Pixelwise binarization with selectional auto-encoders in Keras"
readme = "README.md"
keywords = []
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.8, <3.12"
authors = [
    {name = "Vahid Rezanezhad"},
    {name = "Staatsbibliothek zu Berlin - Preußischer Kulturbesitz"},
    {name = "Janik Haitz", email = "jahtz.dev@proton.me"},
    {name = "Centre for Philology and Digitality (ZPD), University of Würzburg"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Image Processing",
]
dependencies = [
    "tensorflow < 2.13",
    "opencv-python ~= 4.11.0.86",
    "rich ~= 14.0.0",
    "click ~=8.1.8"
]

[project.urls]
Homepage = "https://www.uni-wuerzburg.de/zpd/"
Repository = "https://github.com/jahtz/nlbin"

[project.scripts]
sbbbin = "sbbbin.cli:cli"