version: 2.1

jobs:
  build-python:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - ocrd-resources-{{ checksum "requirements.txt" }}-{{ checksum "Makefile" }}
      - run: make install
      - run: make models
      - save_cache:
          key: ocrd-resources-{{ checksum "requirements.txt" }}-{{ checksum "Makefile" }}
          paths:
            ocrd-resources
      - run: make test
    resource_class: large


workflows:
  build:
    jobs:
      - build-python:
          matrix:
            parameters:
              python-version: ['3.8', '3.9', '3.10', '3.11']

